snacks=["Doughnut","Cookies","Fishpie","Meatpie","Crackers","Garri"]
print("Length of list: ",len(snacks))
print("First element is : ",snacks[0])
print("Last element is: ", snacks[5])
snacks.append("Ice cream")
print("updated list: ", snacks)
snacks.remove("Garri")
print("updated list: ", snacks)
snacks.sort()
print("updated list: ", snacks)
snacks.pop(4)
print("updated list: ", snacks)
snacks.reverse()
print("reversed list: ", snacks)
print("multiplication list:", snacks*2)
snacks=snacks[:5] #slice
print("sliced list: ", snacks)
snacks.clear()
print("updated list: ", snacks)